### ISSUE TITLE
Support PO generation for Selenium

### ISSUE THREAD

**Issue by Supreme85** [anisa07/jdi-plugin#33]
1. Добавить
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
удалить все остальные импорты

2. Не добавлять Аннотации JPage и JSite
Не генерировать Site, не добавлять WebPage к странице
3. Composite - игнорировать рулы. Не создавать секций (все элементы на странице)

4. Заменить
Только Simple Elements
вместо @Css("css-locator") TextField email;
надо    @FindBy(css = "css-locator") public WebElement email;

вместо @XPath("xpath-locator") Button submit;
надо    @FindBy(xpath = "xpath-locator") public WebElement submit;
5. Complex игнорировать

**Comment by anisa07** [comment]
Done
